# This is a basic workflow to help you get started with Actions
name: Hello actions runner controller

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install packages
        run: sudo apt install clang-11 --install-suggests
        
      # Runs a single command using the runners shell
      - name: build
        run: clang -o hello-arc-c hello-arc.c

      # Runs docker hello-world
      - name: run
        run: ./hello-arc-c
